name: Main

on:
    push:
        branches:
            - main

concurrency:
    group: ${{ github.repository }}-main
    cancel-in-progress: true

jobs:
    StaticAnalysis:
        name: StaticAnalysis
        uses: EncoreDigitalGroup/ci-workflows/.github/workflows/php_staticAnalysis.yml@v3
        with:
            phpVersion: '8.3'
            path: 'src/'
            branch: ${{ github.head_ref }}

    Tests:
        name: Tests
        uses: EncoreDigitalGroup/ci-workflows/.github/workflows/php_test.yml@v3
        with:
            phpVersion: '8.3'
            branch: ${{ github.head_ref }}
