name: Pull Request

on:
    push:
        branches:
            - main

concurrency:
    group: ${{ github.repository }}-${{ github.event.pull_request.number }}-main
    cancel-in-progress: true

jobs:
    StaticAnalysis:
        name: StaticAnalysis
        uses: EncoreSoftware/ci-pipelines/.github/workflows/php_staticAnalysis.yml@v3
        with:
            composerAuthJson: ${{ vars.COMPOSER_AUTH_JSON }}
            phpVersion: '8.3'
            path: 'src/'
            branch: ${{ github.head_ref }}

    Tests:
        name: Tests
        uses: EncoreSoftware/ci-pipelines/.github/workflows/php_test.yml@v3
        with:
            composerAuthJson: ${{ vars.COMPOSER_AUTH_JSON }}
            phpVersion: '8.3'
            branch: ${{ github.head_ref }}