name: Release

on:
    push:
        tags:
            - 'v[0-9]+.[0-9]+.[0-9]+-rc[0-9]+'
            - '!v[0-9]+.[0-9]+.[0-9]+'

permissions:
    contents: write

jobs:
    CreatePreRelease:
        name: Create Pre-Release
        runs-on: ubuntu-latest
        steps:
            -   name: Create Pre-Release
                uses: EncoreDigitalGroup/ci-workflows/actions/github/createRelease@v3
                with:
                    generateReleaseNotes: true
                    isDraft: false
                    preRelease: true
                    repository: ${{ github.repository }}
                    tagName: ${{ github.ref_name }}
                    token: ${{ secrets.GITHUB_TOKEN }}
