name: Release

on:
    push:
        tags:
            - 'v[0-9]+.[0-9]+.[0-9]+'
            - '!v[0-9]+.[0-9]+.[0-9]+-rc[0-9]+'

jobs:
    CreateRelease:
        name: Create Release
        uses: EncoreDigitalGroup/ci-workflows/actions/github/createRelease@v3
        permissions:
            contents: write
        with:
            generateReleaseNotes: true
            isDraft: false
            repository: ${{ github.repository }}
            tagName: ${{ github.head_ref }}
            token: ${{ secrets.GITHUB_TOKEN }}